### PR TITLE
add parse and validation errors to JSON suite

### PR DESCRIPTION
**Pull request by nchidsey**
Relating to [Issue 6](https://github.com/schyntax/schyntax/issues/6), this adds JSON structure support and test cases for some parse and validation errors.  So far, this branch does not include changes for testing `ValidTimeNotFoundError`s.  As mentioned in the issue, this currently has a parse error index of 0 for empty schedules, though the index could change.  Also worth mentioning that the reference implementation might conflict on at least one, `minute(monday)`.

### CODE REVIEW

**Comment by bretcope** [comment]
This looks like a great start. I'm going to try it out in the C# this weekend.

**Comment by nchidsey** [comment]
What do you think about adding an optional comment or description to the test cases?  Many test cases are obvious, but some are more subtle and it may not be clear what they are testing.  I took the liberty of using the top-level group names for that in the commits above, but I think a higher granularity would be helpful for a few cases.

**Comment by bretcope** [comment]
I don't have any problem with adding an optional "desc" property.

**Comment by bretcope** [comment]
This looks good, with one exception. The `parseErrorIndex` for `dates(1/-1)` should be 8 instead of 6 because the error is on the minus sign, not the start of the date value. I'll merge this and make that fix.

I have the C# implementation ready to go. I'll get the others setup soon.

**Comment by bretcope** [comment]
By the way, thanks for these tests. They mostly caught some of the deficiencies in error reporting, but they also caught a couple of parser bugs, including one which caused an infinite loop. Good work.

I did reorganize them a little bit in order to consolidate the number of test groups added to three, but everything you added is in there.

**Comment by nchidsey** [comment]
Excellent. I like your regrouping better. Happy to help.

**Pull request merged**
